import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { ClipboardList, Search, LogOut, ArrowLeft } from 'lucide-react'

export default async function ProtectedPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/auth/login')

  const { data: requests } = await supabase.from('maintenance_requests').select('id, request_number, asset_number, problem, priority, status, created_at').order('created_at', { ascending: false }).limit(25)

  return <div className="internal-shell"><header className="internal-header"><a href="/" className="brand-mark">maint<span>en</span>ance</a><nav className="top-nav" aria-label="Main navigation"><a href="/">Home</a><a className="active" href="/protected">Work Orders</a><a href="/protected">Customers</a><a href="/protected">Equipment</a></nav><div className="user-chip"><span className="avatar">{user.email?.slice(0, 2).toUpperCase() || 'AD'}</span><span className="user-name">{user.email}</span><span className="role-label">ADMIN</span></div></header><main className="internal-content"><a className="back-link" href="/"><ArrowLeft data-icon="inline-start" /> Home</a><section className="welcome-row"><div><p className="eyebrow">Operational workspace</p><h1>Work orders</h1><p className="sub">รายการงานซ่อมและงานที่ต้องติดตาม</p></div><form action="/auth/signout" method="post"><button className="outline-action" type="submit"><LogOut data-icon="inline-start" /> ออกจากระบบ</button></form></section><section className="search-panel"><Search data-icon="inline-start" /><input placeholder="ค้นหาเลขที่งาน อุปกรณ์ หรือปัญหา" aria-label="Search work orders" /><span className="search-hint">{requests?.length ?? 0} รายการ</span></section><section className="surface work-order-surface"><div className="section-heading"><div><p className="eyebrow">Maintenance queue</p><h2>All work orders</h2></div><span className="role-label">ADMIN / DEV</span></div><div className="order-list">{requests?.length ? requests.map((request) => <article className="order-row" key={request.id}><div className="order-main"><span className="order-id">{request.request_number}</span><h3>{request.problem}</h3><p>{request.asset_number} <span>·</span> {new Date(request.created_at).toLocaleDateString('th-TH')}</p></div><div className="order-meta"><span className={`status status-${request.status.toLowerCase().replaceAll('_', '-')}`}>{request.status.replaceAll('_', ' ')}</span><span className={`priority priority-${request.priority.toLowerCase()}`}>{request.priority}</span></div></article>) : <div className="empty-message"><ClipboardList /> ยังไม่มีรายการงานซ่อม</div>}</div></section></main><footer className="internal-footer"><span>Maintenance System</span><span>{user.email}</span><a href="/">กลับหน้าหลัก</a></footer></div>
}
